<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Unofficial .NET wrapper of the TMetric REST APIs.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RootNamespace>TMetric</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TMetric.NET.Tests" />
    <None Include="$(SrcDirectory)\..\README.md" Pack="True" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ESCd.Extensions.Http" Version="1.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net.Http.Json" />
  </ItemGroup>

</Project>
