<Project>

  <PropertyGroup Condition=" '$(IsTestProject)' == 'true' ">
    <IsAotCompatible>false</IsAotCompatible>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>CA1707;CA1869;CS1591;IL2026;SA1600</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition=" '$(IsTestProject)' == 'true' ">
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.console" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />

    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup Condition=" '$(RunAnalyzers)' == 'true' ">
    <!-- Include editorconfig (Visual Studio expects editorconfigs in the root of projects). More info here: https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019#file-hierarchy-and-precedence -->
    <None Include="$(SrcDirectory)\..\.editorconfig" Visible="false" />

    <!-- Include reference to .NET/C# code analyzers -->
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="SetPackageMetadata" AfterTargets="MinVer" BeforeTargets="GenerateNuspec;Pack">
    <PropertyGroup>
      <InformationalVersion>$(PackageVersion)</InformationalVersion>
      <InformationalVersion Condition=" '$(MinVerBuildMetadata)' != '' ">$(InformationalVersion)+$(MinVerBuildMetadata)</InformationalVersion>
      <PackageTags>$(PackageTags);TMetric;Time-Tracking</PackageTags>
    </PropertyGroup>
  </Target>

</Project>