<Project>

  <PropertyGroup>
    <ContinuousIntegrationBuild Condition=" '$(GITHUB_ACTIONS)' == 'true' ">true</ContinuousIntegrationBuild>

    <!-- Create a property to easily reference the root of the `src` folder -->
    <SrcDirectory>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</SrcDirectory>
  </PropertyGroup>

  <PropertyGroup>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <DefaultItemExcludesInProjectFolder>$(DefaultItemExcludesInProjectFolder);packages.lock.json;</DefaultItemExcludesInProjectFolder>
    <Deterministic>true</Deterministic>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <Features>strict</Features>
    <GenerateDocumentationFile>$(ContinuousIntegrationBuild)</GenerateDocumentationFile>
    <!-- <GenerateDocumentationFile>true</GenerateDocumentationFile> -->
    <ImplicitUsings>true</ImplicitUsings>
    <IncludeSymbols>true</IncludeSymbols>
    <IsAotCompatible>true</IsAotCompatible>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

    <!-- Disable legacy analyzers and enable NET/Roslyn analyzers -->
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RunAnalyzers>true</RunAnalyzers>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <AnalysisLevel>latest-recommended</AnalysisLevel>

    <TargetFrameworks>net9.0</TargetFrameworks>
  </PropertyGroup>

  <!-- Git Versioning + Metadata -->
  <PropertyGroup>
    <MinVerDefaultPreReleaseIdentifiers>rc.0</MinVerDefaultPreReleaseIdentifiers>
    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!-- NuGet/AssemblyInfo -->
  <PropertyGroup>
    <Authors>cryptoc1</Authors>
    <Copyright>$([System.DateTime]::Now.Year) Escape Developers</Copyright>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/cryptoc1/TMetric.NET</PackageProjectUrl>
    <RepositoryUrl>https://github.com/cryptoc1/TMetric.NET.git</RepositoryUrl>
    <Title>$(AssemblyName)</Title>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Collections" />
  </ItemGroup>

</Project>